source 'https://github.com/CocoaPods/Specs.git'

target 'MRGTraitCollection_Example', :exclusive => true do
  pod "MRGTraitCollection", :path => "../"
end

target 'MRGTraitCollection_Tests', :exclusive => true do
  pod "MRGTraitCollection", :path => "../"
end
